/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise { 'name' : string, 'sets' : Array<Set> }
export interface Goal {
  'title' : string,
  'unit' : string,
  'progress' : number,
  'targetDate' : bigint,
  'targetValue' : number,
}
export interface PersonalRecord {
  'maxWeight' : number,
  'exerciseName' : string,
  'maxReps' : bigint,
}
export interface ProfilePublic { 'displayName' : string }
export type PublicGoals = Array<Goal>;
export interface Set { 'reps' : bigint, 'weightKg' : number }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'id' : number,
  'date' : bigint,
  'name' : string,
  'exercises' : Array<Exercise>,
  'durationMinutes' : bigint,
}
export interface WorkoutStats {
  'totalWorkouts' : bigint,
  'totalVolumeKg' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGoal' : ActorMethod<[Goal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'deleteWorkout' : ActorMethod<[number], undefined>,
  'getCallerUserProfile' : ActorMethod<[], ProfilePublic>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoals' : ActorMethod<[], PublicGoals>,
  'getPersonalRecords' : ActorMethod<[], Array<PersonalRecord>>,
  'getStats' : ActorMethod<[], WorkoutStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [ProfilePublic]>,
  'getWorkout' : ActorMethod<[number], Workout>,
  'getWorkouts' : ActorMethod<[], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkout' : ActorMethod<[Workout], number>,
  'saveCallerUserProfile' : ActorMethod<[ProfilePublic], undefined>,
  'updateGoal' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];