/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Goal = IDL.Record({
  'title' : IDL.Text,
  'unit' : IDL.Text,
  'progress' : IDL.Float64,
  'targetDate' : IDL.Int,
  'targetValue' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfilePublic = IDL.Record({ 'displayName' : IDL.Text });
export const PublicGoals = IDL.Vec(Goal);
export const PersonalRecord = IDL.Record({
  'maxWeight' : IDL.Float64,
  'exerciseName' : IDL.Text,
  'maxReps' : IDL.Nat,
});
export const WorkoutStats = IDL.Record({
  'totalWorkouts' : IDL.Nat,
  'totalVolumeKg' : IDL.Float64,
});
export const Set = IDL.Record({ 'reps' : IDL.Nat, 'weightKg' : IDL.Float64 });
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'sets' : IDL.Vec(Set),
});
export const Workout = IDL.Record({
  'id' : IDL.Nat8,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'durationMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGoal' : IDL.Func([Goal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'deleteWorkout' : IDL.Func([IDL.Nat8], [], []),
  'getCallerUserProfile' : IDL.Func([], [ProfilePublic], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoals' : IDL.Func([], [PublicGoals], ['query']),
  'getPersonalRecords' : IDL.Func([], [IDL.Vec(PersonalRecord)], ['query']),
  'getStats' : IDL.Func([], [WorkoutStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProfilePublic)],
      ['query'],
    ),
  'getWorkout' : IDL.Func([IDL.Nat8], [Workout], ['query']),
  'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkout' : IDL.Func([Workout], [IDL.Nat8], []),
  'saveCallerUserProfile' : IDL.Func([ProfilePublic], [], []),
  'updateGoal' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Goal = IDL.Record({
    'title' : IDL.Text,
    'unit' : IDL.Text,
    'progress' : IDL.Float64,
    'targetDate' : IDL.Int,
    'targetValue' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfilePublic = IDL.Record({ 'displayName' : IDL.Text });
  const PublicGoals = IDL.Vec(Goal);
  const PersonalRecord = IDL.Record({
    'maxWeight' : IDL.Float64,
    'exerciseName' : IDL.Text,
    'maxReps' : IDL.Nat,
  });
  const WorkoutStats = IDL.Record({
    'totalWorkouts' : IDL.Nat,
    'totalVolumeKg' : IDL.Float64,
  });
  const Set = IDL.Record({ 'reps' : IDL.Nat, 'weightKg' : IDL.Float64 });
  const Exercise = IDL.Record({ 'name' : IDL.Text, 'sets' : IDL.Vec(Set) });
  const Workout = IDL.Record({
    'id' : IDL.Nat8,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'durationMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGoal' : IDL.Func([Goal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'deleteWorkout' : IDL.Func([IDL.Nat8], [], []),
    'getCallerUserProfile' : IDL.Func([], [ProfilePublic], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoals' : IDL.Func([], [PublicGoals], ['query']),
    'getPersonalRecords' : IDL.Func([], [IDL.Vec(PersonalRecord)], ['query']),
    'getStats' : IDL.Func([], [WorkoutStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProfilePublic)],
        ['query'],
      ),
    'getWorkout' : IDL.Func([IDL.Nat8], [Workout], ['query']),
    'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkout' : IDL.Func([Workout], [IDL.Nat8], []),
    'saveCallerUserProfile' : IDL.Func([ProfilePublic], [], []),
    'updateGoal' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };